apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tejsk\Downloads\kompose-windows-amd64.exe --file ..\Nextcloud\Sync\Faks 3.letnik\DevOps\docker\compose.yaml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tejsk\Downloads\kompose-windows-amd64.exe --file ..\Nextcloud\Sync\Faks 3.letnik\DevOps\docker\compose.yaml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME_FILE
              value: /run/secrets/db-name
            - name: DB_PASSWORD_FILE
              value: /run/secrets/db-password
            - name: DB_USER_FILE
              value: /run/secrets/db-user
            - name: REDIS_HOST
              value: redis
          image: app
          name: app
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /run/secrets
              name: db-user
              subPath: db-user
            - mountPath: /run/secrets
              name: db-name
              subPath: db-name
      restartPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: db-user
          secret:
            items:
              - key: db-user
                path: db-user
            secretName: db-user
        - name: db-name
          secret:
            items:
              - key: db-name
                path: db-name
            secretName: db-name
