apiVersion: v1
data:
  cloudflare.ini: dns_cloudflare_api_token = CyFvVlCwZyr4XDl6ut4R2vmEwB83nGOPgCzuCeqP
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: certbot
  name: certbot-cm1
