apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\tejsk\Downloads\kompose-windows-amd64.exe --file ..\Nextcloud\Sync\Faks 3.letnik\DevOps\docker\compose.yaml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\tejsk\Downloads\kompose-windows-amd64.exe --file ..\Nextcloud\Sync\Faks 3.letnik\DevOps\docker\compose.yaml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB_FILE
              value: /run/secrets/db-name
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/db-password
            - name: POSTGRES_USER_FILE
              value: /run/secrets/db-user
          image: db
          name: db
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /run/secrets
              name: db-user
              subPath: db-user
            - mountPath: /run/secrets
              name: db-name
              subPath: db-name
            - mountPath: /var/lib/postgresql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - name: db-user
          secret:
            items:
              - key: db-user
                path: db-user
            secretName: db-user
        - name: db-name
          secret:
            items:
              - key: db-name
                path: db-name
            secretName: db-name
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
